<a href="https://colab.research.google.com/github/AgarwalMayank2/Face_Detection/blob/KNN_Tavishi/KNN_PRMLproj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [92]:
# mount google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Reading CNN features

In [3]:
url_filtered_CNN_features_dataset = 'https://raw.githubusercontent.com/AgarwalMayank2/Face_Detection/refs/heads/main/processed_dataset/filtered_CNN_features_dataset.csv' #for CNN limited
df_cnn = pd.read_csv(url_filtered_CNN_features_dataset) # reading url for extracted CNN_features_dataset_limited.csv

In [4]:
df_cnn.head(10)

Unnamed: 0         0         1         2         3         4         5  \
0           0  0.266585  1.337187  1.352905  0.100848  1.880685  0.059888   
1           1  0.355948  0.750634  0.909794  0.188214  0.680066  0.221442   
2           2  0.267111  1.015316  1.154480  0.131544  1.066389  0.024949   
3           3  0.260295  0.882900  0.885955  0.106698  2.663052  0.057836   
4           4  0.347203  0.623839  0.817085  0.212599  1.026321  0.176634   
5           5  0.354952  0.935169  1.313525  0.161971  0.743334  0.075382   
6           6  0.491479  1.098953  0.935011  0.099713  0.859047  0.125197   
7           7  0.076298  1.872830  1.156564  0.151697  1.786531  0.004271   
8           8  0.443961  1.489843  1.034748  0.054299  1.201338  0.475425   
9           9  0.265048  1.558320  0.774199  0.302818  0.905585  0.152244   

          6         7         8  ...      2039      2040      2041      2042  \
0  2.773605  0.115643  0.138749  ...  0.039434  0.071662  0.733759  1.643910   
1  3.089571  0.342022  0.087186  ...  0.093867  0.089694  0.859610  1.764073   
2  3.701925  0.145037  0.082419  ...  0.080086  0.089589  0.663708  1.854499   
3  1.854394  0.209269  0.103750  ...  0.181255  0.182038  0.397535  1.222931   
4  2.486715  0.426571  0.345026  ...  0.267895  0.136346  0.713298  0.978184   
5  2.913061  0.339807  0.038969  ...  0.042886  0.094991  0.731441  1.846496   
6  2.448608  0.194795  0.171454  ...  0.197234  0.036094  0.552411  1.532099   
7  2.473813  0.183758  0.190911  ...  0.025632  0.110004  0.524370  1.041115   
8  3.003049  0.170383  0.172904  ...  0.170266  0.155772  1.335769  1.501814   
9  2.703004  0.314053  0.539273  ...  0.076195  0.142454  0.670869  1.724953   

       2043      2044      2045      2046      2047         2048  
0  0.041306  1.488236  0.048181  0.247783  0.300232  Paul_Bremer  
1  0.250430  1.133540  0.004091  0.153542  0.236034  Paul_Bremer  
2  0.078751  1.240009  0.065222  0.105058  0.227633  Paul_Bremer  
3  0.007285  0.878194  0.016247  0.110492  0.129523  Paul_Bremer  
4  0.059828  1.008205  0.042905  0.028597  0.199120  Paul_Bremer  
5  0.061113  0.960774  0.152283  0.094486  0.294108  Paul_Bremer  
6  0.195461  0.562803  0.054066  0.242185  0.097366  Paul_Bremer  
7  0.171625  1.456280  0.096045  0.074930  0.214463  Paul_Bremer  
8  0.096764  1.345042  0.470579  0.327874  0.116694  Paul_Bremer  
9  0.110348  1.263562  0.008221  0.099455  0.174265  Paul_Bremer  

[10 rows x 2050 columns]

# Train/Test split - for CNN dataset

In [7]:
# Separate features and labels
X_cnn = df_cnn.iloc[:, :-1]
y_cnn = df_cnn.iloc[:, -1]

# Encode labels (alphabetically)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y_cnn)
# encoding is benificial as working on numbers is lot easier than working on string

# Ensure stratified split (16 training, 4 testing per class)
X_train_cnn, X_test_cnn, y_train_cnn, y_test_cnn = train_test_split(X_cnn, y_encoded, test_size=1/5, random_state=42, stratify=y_encoded)

# Normalize features
scaler = StandardScaler()
X_train_cnn = scaler.fit_transform(X_train_cnn)
X_test_cnn = scaler.transform(X_test_cnn)

print(f"Dataset size: {df_cnn.shape}")
print(f"Training size: {X_train_cnn.shape}, Testing size: {X_test_cnn.shape}")

Dataset size: (4324, 2050)
Training size: (3459, 2049), Testing size: (865, 2049)


In [23]:
print(y_train_cnn[:10])

[ 36 134 146   6  41  23  61  28 134  53]


# Reading HoG features

In [ ]:
url_filtered_HoG_features_dataset='/content/drive/My Drive/filtered_HOG_features_dataset.csv'
df_hog=pd.read_csv(url_filtered_HoG_features_dataset)

In [ ]:
df_hog.head(10)

# Train/Test split - for HoG dataset

In [ ]:
# Separate features and labels
X_hog = df_hog.iloc[:, :-1]
y_hog = df_hog.iloc[:, -1]

# Encode labels (alphabetically)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y_hog)
# encoding is benificial as working on numbers is lot easier than working on string

# Ensure stratified split (16 training, 4 testing per class)
X_train_hog, X_test_hog, y_train_hog, y_test_hog = train_test_split(X_hog, y_encoded, test_size=1/5, random_state=42, stratify=y_encoded)

# Normalize features
scaler = StandardScaler()
X_train_hog = scaler.fit_transform(X_train_hog)
X_test_hog = scaler.transform(X_test_hog)

print(f"Dataset size: {df_hog.shape}")
print(f"Training size: {X_train_hog.shape}, Testing size: {X_test_hog.shape}")

# Reading LBP features

In [9]:
url_filtered_lbp_features = 'https://raw.githubusercontent.com/AgarwalMayank2/Face_Detection/refs/heads/main/processed_dataset/filtered_LBP_features_dataset.csv'
df_LBP = pd.read_csv(url_filtered_lbp_features)

In [10]:
df_LBP.head(10)

Unnamed: 0       0      1      2      3      4     5      6      7      8  \
0           0   589.0   57.0  319.0  205.0   67.0   4.0  195.0  466.0  370.0   
1           1  1012.0  113.0  383.0  203.0   76.0  11.0  205.0  369.0  505.0   
2           2   920.0   92.0  288.0  152.0  107.0  18.0  192.0  403.0  313.0   
3           3  1068.0   85.0  447.0  298.0   90.0  11.0  293.0  732.0  546.0   
4           4   510.0   43.0  304.0  189.0   47.0   8.0  201.0  387.0  296.0   
5           5   678.0   65.0  173.0  131.0   66.0  14.0  114.0  255.0  292.0   
6           6   668.0   62.0  344.0  187.0   60.0  10.0  218.0  347.0  330.0   
7           7   745.0   74.0  267.0  218.0   80.0  10.0  180.0  363.0  376.0   
8           8   428.0   45.0  268.0  222.0   44.0   6.0  210.0  430.0  265.0   
9           9  1154.0  103.0  354.0  234.0  113.0  16.0  260.0  374.0  473.0   

   ...    247     248    249   250    251    252    253    254      255  \
0  ...  474.0  1924.0  612.0  26.0  357.0  592.0  523.0  328.0   6088.0   
1  ...  591.0  2086.0  681.0  29.0  447.0  699.0  535.0  486.0  13472.0   
2  ...  461.0  1812.0  579.0  41.0  428.0  597.0  411.0  374.0  11673.0   
3  ...  727.0  2150.0  650.0  32.0  374.0  564.0  585.0  367.0   5449.0   
4  ...  405.0  3263.0  588.0  36.0  307.0  593.0  350.0  328.0   4606.0   
5  ...  366.0  2675.0  577.0  43.0  556.0  678.0  313.0  581.0  17998.0   
6  ...  510.0  2106.0  678.0  51.0  612.0  660.0  435.0  639.0  13194.0   
7  ...  590.0  2008.0  622.0  44.0  417.0  545.0  410.0  380.0   9406.0   
8  ...  343.0  1964.0  668.0  35.0  315.0  537.0  433.0  283.0   3225.0   
9  ...  578.0  1488.0  599.0  30.0  396.0  587.0  482.0  399.0  11423.0   

          256  
0  Tim_Henman  
1  Tim_Henman  
2  Tim_Henman  
3  Tim_Henman  
4  Tim_Henman  
5  Tim_Henman  
6  Tim_Henman  
7  Tim_Henman  
8  Tim_Henman  
9  Tim_Henman  

[10 rows x 258 columns]

# Train/Test split - for LBP dataset

In [14]:
# Separate features and labels
X_LBP = df_LBP.iloc[:, :-1]
y_LBP = df_LBP.iloc[:, -1]

# Encode labels (alphabetically)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y_LBP)
# encoding is benificial as working on numbers is lot easier than working on string

# Ensure stratified split (16 training, 4 testing per class)
X_train_LBP, X_test_LBP, y_train_LBP, y_test_LBP = train_test_split(X_LBP, y_encoded, test_size=1/5, random_state=42, stratify=y_encoded)

# Normalize features
scaler = StandardScaler()
X_train_LBP = scaler.fit_transform(X_train_LBP)
X_test_LBP = scaler.transform(X_test_LBP)

print(f"Dataset size: {df_LBP.shape}")
print(f"Training size: {X_train_LBP.shape}, Testing size: {X_test_LBP.shape}")

Dataset size: (4324, 258)
Training size: (3459, 257), Testing size: (865, 257)


# Applying PCA for dimensionality reduction

In [1]:
from sklearn.decomposition import PCA

# PCA on CNN features

In [2]:
pca=PCA(n_components=300)

X_train_cnn_pca=pca.fit_transform(X_train_cnn)
X_test_cnn_pca=pca.transform(X_test_cnn)

print(X_train_cnn_pca.shape)
print(X_test_cnn_pca.shape)

NameError: name 'X_train_cnn' is not defined

# PCA on HoG features

In [ ]:
pca=PCA(n_components=1000)

X_train_hog_pca=pca.fit_transform(X_train_hog)
X_test_hog_pca=pca.transform(X_test_hog)

print(X_train_hog_pca.shape)
print(X_test_hog_pca.shape)

# PCA on LBP features

In [16]:
pca=PCA(n_components=50)

X_train_LBP_pca=pca.fit_transform(X_train_LBP)
X_test_LBP_pca=pca.transform(X_test_LBP)

print(X_train_LBP_pca.shape)
print(X_test_LBP_pca.shape)

(3459, 50)
(865, 50)


# Combining all features

In [ ]:
combined_X_train = np.concatenate((X_train_cnn_pca, X_train_hog_pca, X_train_LBP_pca))
combined_X_test = np.concatenate((X_test_cnn_pca, X_test_hog_pca, X_test_LBP_pca))

In [17]:
y_train = y_train_cnn
y_test = y_test_cnn

print(y_train[:10])
print(y_test[:10])

[ 36 134 146   6  41  23  61  28 134  53]
[ 91  60 128  35  11 103  50 111  89  80]


# Check Printing

In [91]:
# for i in range(X_test_cnn_pca.shape[0]):
#   if i%100==0:
#     print(X_test_cnn_pca[i,:])

In [84]:
for i in range(len(y_test)):
  if i%100==0:
    print(label_encoder.inverse_transform([y_test[i]])[0])

Laura_Bush
Angelina_Jolie
Andre_Agassi
Mike_Weir
Colin_Powell
John_Negroponte
Dick_Cheney
Vladimir_Putin
Gerhard_Schroeder


# KNN Model

In [85]:
import numpy as np
import math

In [86]:
def euclidean_dist(x,y):
  # x1,y1,z1=x
  # x2,y2,z2=y
  return math.sqrt(sum([(a-b)**2 for a,b in zip(x,y)]))

In [17]:
point1 = [2,3,4]
point2 = [1,2,1]
print(euclidean_dist(point1, point2))

3.3166247903554


In [87]:
k=3

In [88]:
from collections import Counter

In [90]:
predictions=[]
for i in range(combined_X_test.shape[0]):
  distances=[]
  nearest_labels=[]
  for j in range(combined_X_train.shape[0]):
    # append the pair (distance, index) to distances
    distance=euclidean_dist(combined_X_test[i], combined_X_train[j])
    distances.append((distance, j))
  # sorting distances on the basis of first item of pair i.e. distance
  distances.sort(key=lambda x:x[0])
  for k1 in range(k):
    nearest_labels.append(y_train[distances[k1][1]])

  label_counts = Counter(nearest_labels)
  most_common_label = label_counts.most_common(1)[0][0] if nearest_labels else -1

  predictions.append(label_encoder.inverse_transform([most_common_label])[0])

  if i%100==0:
    print(f'Label {i} detected')
    # if most_common_label!=-1:
    #   print(X_test_cnn_pca[i], '\t', label_encoder.inverse_transform([most_common_label])[0])
    # else:
    #   print(X_test_cnn_pca[i], '\t', 'Unknown')

print(predictions)

Label 0 detected
Label 100 detected
Label 200 detected
Label 300 detected
Label 400 detected
Label 500 detected
Label 600 detected
Label 700 detected
Label 800 detected
['Rubens_Barrichello', 'Colin_Powell', 'Carlos_Moya', 'George_W_Bush', 'George_W_Bush', 'Anna_Kournikova', 'Serena_Williams', 'Gray_Davis', 'Colin_Powell', 'Ariel_Sharon', 'George_W_Bush', 'Mohammed_Al-Douri', 'Jose_Maria_Aznar', 'Hugo_Chavez', 'George_W_Bush', 'Arnold_Schwarzenegger', 'Gonzalo_Sanchez_de_Lozada', 'Gerhard_Schroeder', 'Alejandro_Toledo', 'Donald_Rumsfeld', 'Tony_Blair', 'Naomi_Watts', 'Jacques_Chirac', 'Ricardo_Lagos', 'John_Negroponte', 'John_Negroponte', 'Paul_Bremer', 'Jennifer_Garner', 'Colin_Powell', 'Kim_Clijsters', 'Jean_Chretien', 'Tim_Henman', 'Megawati_Sukarnoputri', 'George_W_Bush', 'Megawati_Sukarnoputri', 'George_W_Bush', 'Trent_Lott', 'Carlos_Menem', 'Luiz_Inacio_Lula_da_Silva', 'George_W_Bush', 'Luiz_Inacio_Lula_da_Silva', 'Pierce_Brosnan', 'George_W_Bush', 'Recep_Tayyip_Erdogan', 'Megawa