<a href="https://colab.research.google.com/github/AgarwalMayank2/Face_Detection/blob/SVM_Ekta/Naive_bayes_PRML_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Loading processed dataset to proceed**

**Install important libraries to proceed**

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

## Loading filtered_CNN_features_dataset

In [2]:
url_filtered_CNN_features_dataset = 'https://raw.githubusercontent.com/AgarwalMayank2/Face_Detection/refs/heads/main/processed_dataset/filtered_CNN_features_dataset.csv' #for CNN limited
df_CNN = pd.read_csv(url_filtered_CNN_features_dataset) # reading url for extracted CNN_features_dataset_limited.csv
df_CNN.drop('Unnamed: 0', axis=1, inplace=True)
df_CNN

0         1         2         3         4         5         6  \
0     0.266585  1.337187  1.352905  0.100848  1.880685  0.059888  2.773605   
1     0.355948  0.750634  0.909794  0.188214  0.680066  0.221442  3.089571   
2     0.267111  1.015316  1.154480  0.131544  1.066389  0.024949  3.701925   
3     0.260295  0.882900  0.885955  0.106698  2.663052  0.057836  1.854394   
4     0.347203  0.623839  0.817085  0.212599  1.026321  0.176634  2.486715   
...        ...       ...       ...       ...       ...       ...       ...   
4319  0.110671  0.933532  1.576373  0.047225  0.697608  0.100375  2.509764   
4320  0.250879  1.126343  0.961169  0.032000  0.247225  0.064331  2.297021   
4321  0.101699  1.497757  0.805623  0.210569  1.158021  0.287555  1.315162   
4322  0.108061  0.696727  1.336171  0.016554  0.625865  0.380914  2.106623   
4323  0.158156  1.004157  1.258772  0.539227  0.618928  0.106001  1.849813   

             7         8         9  ...      2039      2040      2041  \
0     0.115643  0.138749  0.056121  ...  0.039434  0.071662  0.733759   
1     0.342022  0.087186  0.234741  ...  0.093867  0.089694  0.859610   
2     0.145037  0.082419  0.253356  ...  0.080086  0.089589  0.663708   
3     0.209269  0.103750  0.149302  ...  0.181255  0.182038  0.397535   
4     0.426571  0.345026  0.375072  ...  0.267895  0.136346  0.713298   
...        ...       ...       ...  ...       ...       ...       ...   
4319  0.342827  0.115562  1.093016  ...  0.161235  0.646160  0.615094   
4320  0.689515  0.502984  0.706359  ...  0.322805  0.402172  0.624546   
4321  0.545735  0.269730  0.630467  ...  0.252010  0.129211  1.347581   
4322  0.466441  0.081740  1.208193  ...  0.168940  0.217983  0.425700   
4323  1.881353  0.015113  0.750354  ...  0.132900  0.234982  0.723592   

          2042      2043      2044      2045      2046      2047  \
0     1.643910  0.041306  1.488236  0.048181  0.247783  0.300232   
1     1.764073  0.250430  1.133540  0.004091  0.153542  0.236034   
2     1.854499  0.078751  1.240009  0.065222  0.105058  0.227633   
3     1.222931  0.007285  0.878194  0.016247  0.110492  0.129523   
4     0.978184  0.059828  1.008205  0.042905  0.028597  0.199120   
...        ...       ...       ...       ...       ...       ...   
4319  1.555704  0.093572  0.744401  0.186377  0.036658  0.164960   
4320  1.822085  0.377166  0.638106  0.105163  0.089668  0.067495   
4321  1.599726  0.049081  2.030167  0.162992  0.033966  0.037959   
4322  1.362742  0.245273  0.682824  0.271875  0.023275  0.111986   
4323  1.744867  0.163148  0.673565  0.267524  0.054689  0.976268   

               2048  
0       Paul_Bremer  
1       Paul_Bremer  
2       Paul_Bremer  
3       Paul_Bremer  
4       Paul_Bremer  
...             ...  
4319  Charles_Moose  
4320  Charles_Moose  
4321  Charles_Moose  
4322  Charles_Moose  
4323  Charles_Moose  

[4324 rows x 2049 columns]

In [3]:
# Filter persons with at least 80 images

#dropping those labels whose number of datapoints are less than 80
# Get the counts of each label
label_counts = df_CNN['2048'].value_counts()

# Filter out labels with counts less than 80
labels_to_keep = label_counts[label_counts >= 80].index

# Filter the DataFrame
df_CNN = df_CNN[df_CNN['2048'].isin(labels_to_keep)]

df_CNN

0         1         2         3         4         5         6  \
207   0.334396  1.031447  0.751403  0.061664  1.358539  0.131194  2.189165   
208   0.052159  1.385429  0.948584  0.242452  0.765526  0.205163  2.773744   
209   0.215924  1.243201  1.040831  0.082872  0.996569  0.093324  3.699462   
210   0.273529  1.568788  1.131568  0.069734  1.060217  0.003534  3.313872   
211   0.209844  1.102461  0.380182  0.109593  0.713786  0.054662  2.087155   
...        ...       ...       ...       ...       ...       ...       ...   
3959  0.312240  1.009504  0.836836  0.018082  0.645396  0.066804  2.271123   
3960  0.318314  1.077076  0.959523  0.018094  0.547238  0.033101  2.574726   
3961  0.344084  0.716365  1.162212  0.025244  1.336606  0.032508  3.778199   
3962  0.349864  0.792629  0.792507  0.079453  1.206452  0.083974  2.950798   
3963  0.304833  0.958092  1.026033  0.099528  0.545396  0.156279  2.959451   

             7         8         9  ...      2039      2040      2041  \
207   0.168872  0.077561  0.128026  ...  0.238129  0.033446  0.691363   
208   0.487321  0.375770  0.297134  ...  0.151970  0.030394  0.931749   
209   0.166822  0.085976  0.420676  ...  0.280522  0.046874  0.933633   
210   0.470634  0.280771  0.550614  ...  0.392776  0.303419  0.718607   
211   0.206262  0.103134  0.152454  ...  0.100046  0.225041  0.373597   
...        ...       ...       ...  ...       ...       ...       ...   
3959  0.094211  0.141208  0.130362  ...  0.292594  0.216060  0.466659   
3960  0.171667  0.403900  0.141492  ...  0.184252  0.081133  0.731656   
3961  0.205079  0.106398  0.161860  ...  0.078263  0.198066  0.789224   
3962  0.072012  0.180612  0.077492  ...  0.130345  0.346125  0.530768   
3963  0.164015  0.254310  0.131672  ...  0.195513  0.086150  0.692803   

          2042      2043      2044      2045      2046      2047  \
207   1.453779  0.023197  1.180975  0.147620  0.132144  0.061259   
208   1.507545  0.074761  1.410434  0.187171  0.037343  0.192220   
209   1.932075  0.076832  1.779623  0.345520  0.009288  0.176782   
210   1.815761  0.034294  1.519493  0.046060  0.031623  0.141197   
211   0.834548  0.102522  0.784862  0.023190  0.141059  0.058093   
...        ...       ...       ...       ...       ...       ...   
3959  0.785201  0.021710  0.663016  0.343248  0.060820  0.134825   
3960  1.326214  0.040101  1.001839  0.011269  0.099451  0.093939   
3961  1.613293  0.019929  1.323015  0.041566  0.020037  0.051515   
3962  1.389377  0.117860  1.205199  0.044289  0.032452  0.238427   
3963  1.279510  0.230788  0.656069  0.018345  0.153180  0.248380   

                 2048  
207   Donald_Rumsfeld  
208   Donald_Rumsfeld  
209   Donald_Rumsfeld  
210   Donald_Rumsfeld  
211   Donald_Rumsfeld  
...               ...  
3959     Colin_Powell  
3960     Colin_Powell  
3961     Colin_Powell  
3962     Colin_Powell  
3963     Colin_Powell  

[1140 rows x 2049 columns]

Splitting dataframe into train and test in 4:1 ratio

In [4]:
# Separate features and labels
X = df_CNN.iloc[:, :-1]
y = df_CNN.iloc[:, -1]

# Encode labels (alphabetically)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
# encoding is benificial as working on numbers is lot easier than working on string

# Ensure stratified split (16 training, 4 testing per class)
X_train_CNN, X_test_CNN, y_train_CNN, y_test_CNN = train_test_split(X, y_encoded, test_size=1/5, random_state=42, stratify=y_encoded)

# Normalize features
scaler = StandardScaler()
X_train_CNN = scaler.fit_transform(X_train_CNN)
X_test_CNN = scaler.transform(X_test_CNN)

print(f"Dataset size: {df_CNN.shape}")
print(f"Training size: {X_train_CNN.shape}, Testing size: {X_test_CNN.shape}")

Dataset size: (1140, 2049)
Training size: (912, 2048), Testing size: (228, 2048)


# Naive Bayes Algorithm

In [6]:
class NaiveBayesClassifier:
    def fit(self, X, y):
        self.classes = np.unique(y)
        self.mean = {}
        self.var = {}
        self.priors = {}

        for c in self.classes:
            X_c = X[y == c]
            self.mean[c] = np.mean(X_c, axis=0)
            self.var[c] = np.var(X_c, axis=0) + 1e-9  # to prevent division by zero
            self.priors[c] = X_c.shape[0] / X.shape[0]

    def calculate_likelihood(self, class_idx, x):
        mean = self.mean[class_idx]
        var = self.var[class_idx]
        exponent = -((x - mean) ** 2) / (2 * var)
        return np.sum(exponent - 0.5 * np.log(2 * np.pi * var))

    def predict(self, X):
        predictions = []
        for x in X:
            posteriors = []
            for c in self.classes:
                log_prior = np.log(self.priors[c])
                log_likelihood = self.calculate_likelihood(c, x)
                posterior = log_prior + log_likelihood
                posteriors.append(posterior)
            predictions.append(np.argmax(posteriors))
        return np.array(predictions)


Training the model and making predictions

In [7]:
model = NaiveBayesClassifier()
model.fit(X_train_CNN, y_train_CNN)
predictions = model.predict(X_test_CNN)

print("Accuracy:", accuracy_score(y_test_CNN, predictions))
print("\nConfusion Matrix:\n", confusion_matrix(y_test_CNN, predictions))
print("\nClassification Report:\n", classification_report(y_test_CNN, predictions, target_names=label_encoder.classes_))

Accuracy: 0.39473684210526316

Confusion Matrix:
 [[22  3  8  3 11]
 [ 5  9  5  2  3]
 [16  6 37  3 44]
 [ 4  0  4  7  7]
 [ 5  2  7  0 15]]

Classification Report:
                    precision    recall  f1-score   support

     Colin_Powell       0.42      0.47      0.44        47
  Donald_Rumsfeld       0.45      0.38      0.41        24
    George_W_Bush       0.61      0.35      0.44       106
Gerhard_Schroeder       0.47      0.32      0.38        22
       Tony_Blair       0.19      0.52      0.28        29

         accuracy                           0.39       228
        macro avg       0.43      0.41      0.39       228
     weighted avg       0.49      0.39      0.41       228

